# Read about factories at http://github.com/thoughtbot/factory_girl

FactoryGirl.define do
	factory :transaction, class: Laundry::PaymentsGateway::TransactionResponse do
		merchant { build(:merchant) }
		record({
			:account_type => "C",
			:acct_trn => "1234153465",
			:amount => "25",
			:attempt_number => "1",
			:billto_address => nil,
			:billto_address2 => nil,
			:billto_city => nil,
			:billto_company_name => nil,
			:billto_email_address => nil,
			:billto_first_name => "John",
			:billto_last_name => "Q. Public",
			:billto_phone => nil,
			:billto_postal_code => nil,
			:billto_state => nil,
			:card_exp_date => nil,
			:card_type => nil,
			:cardholder_name => nil,
			:check_number => nil,
			:consumer_id => nil,
			:consumer_order_id => "transaction432",
			:convenience_fee => "0",
			:convenience_fee_principal => "0",
			:debit_credit => "C",
			:entered_by => nil,
			:entry_class_code => nil,
			:entry_description => nil,
			:ip_address => "192.168.1.1",
			:item_description => nil,
			:line_items => nil,
			:merchant_data1 => nil,
			:merchant_data2 => nil,
			:merchant_data3 => nil,
			:merchant_data4 => nil,
			:merchant_data5 => nil,
			:merchant_data6 => nil,
			:merchant_data7 => nil,
			:merchant_data8 => nil,
			:merchant_data9 => nil,
			:merchant_id => "1",
			:origination_date =>  DateTime.parse("Wed, 29 Aug 2012 00:00:00 +0000"),
			:response  =>  {
				:auth_code => "1234235",
				:avs_result => nil,
				:last4 => "1234",
				:merchant_client_id => "1",
				:preauth_code => nil,
				:preauth_description => nil,
				:preauth_neg_report => nil,
				:preauth_result => nil,
				:response_code => "A01",
				:response_description => "APPROVED",
				:response_type => "A",
				:status => "Funded",
				:transaction_id => "gewragwegew-34-fqwf4fa"
			},
			:sales_tax_amount => "0",
			:service_fee => "0",
			:service_fee_principal => "0",
			:shipto_address => nil,
			:shipto_address2 => nil,
			:shipto_city => nil,
			:shipto_freight_amount => "0",
			:shipto_name => nil,
			:shipto_postal_code => nil,
			:shipto_state => nil,
			:total_amount => "25",
			:transaction_id => "gewragwegew-34-fqwf4fa",
			:ts_created => DateTime.parse("Wed, 29 Aug 2012 00:00:00 +0000"),
			:updated_date => DateTime.parse("Wed, 29 Aug 2012 00:00:00 +0000"),
			:user_defined => nil,
			:wallet_id => nil,
			:"@xmlns:i" => "http://www.w3.org/2001/XMLSchema-instance"
		})
	end
end
